dataset:
    name: 'cifar10'
    map_funcs: 'yuv_huffman'
    num_bitplanes: 8
    d_v: 4
    d_c: 8
    snr: 8
    seed: 42
    patch_w: 1
    patch_h: 8

model:
    name: 'gru'
    gru_units: 32

num_runs: 5

training:
    output_dir: "exp0"
    learning_rate: 0.001
    per_device_train_batch_size: 64
    per_device_eval_batch_size: 64
    gradient_accumulation_steps: 1
    gradient_checkpointing: false
    max_grad_norm: 
    bf16: false
    fp16: false
    num_train_epochs: 30
    weight_decay: 0.01

    lr_scheduler_type: "cosine"
    warmup_ratio: 0.05

    do_eval: true
    evaluation_strategy: "epoch"
    eval_steps: 10
    logging_strategy: "epoch"
    logging_steps: 10
    save_strategy: "epoch"
    save_total_limit: 1
    report_to: 'tensorboard'
